
jenkins:
  image: jenkins
  ports:
    - 8080:8080
    - 9090:9090
  volumes:
    - ./war/target/jenkins.war:/usr/share/jenkins/jenkins.war
  environment:
    - JAVA_OPTS="-Dcom.sun.management.jmxremote.local.only=false -Djava.net.preferIPv4Stack=true -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
